apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - pdb.yaml
namespace: managed-prod
patchesStrategicMerge:
  - image.yaml
  - resources.yaml
  - http-route.yaml
