enableGlobalCache: true

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

preferInteractive: true

npmMinimalAgeGate: 7d

npmPreapprovedPackages:
  - "@axinom/*"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
