approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: true

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 7d

npmPreapprovedPackages:
  - "@axinom/*"

npmRegistryServer: "https://registry.npmjs.org"

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.17.1.cjs
