trigger: none

pr:
  - main

pool:
  vmImage: ubuntu-latest
  demands: project_navy

variables:
  yarnCacheFolder: /home/vsts/.yarn/berry/cache
  NODE_OPTIONS: --max-old-space-size=8192

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
        yarn
      path: $(yarnCacheFolder)
    displayName: Cache yarn packages

  - script: yarn install --immutable
    displayName: 'Install dependencies'

  - script: yarn build
    displayName: 'Build the App'

  - script: yarn test:ci
    displayName: 'Run tests for the App'
